### ISSUE TITLE
Lowercasing in the ES DSL transformation

### ISSUE THREAD

**Issue by kbrabrand** [imbo/imbo-metadata-search#10]
I notice the AST/DSL transformation lowercase all values. I guess this is intentional and wanted.

Values are lowercase as part of the index-time processing and right now a search for cat results in a hit for Cat.

This is more of an implementation detail, but I guess we should probably lowercase the values nevertheless. Thoughts?

**Comment by matslindh** [comment]
Lowercasing tokens should not be performed before indexing - only as part of the analysis / indexing chain. The returned values to the server should be in identical casing as when indexing. Hitting Cat when searching for cat is perfectly OK, but the token returned should be in the same case as when indexed.

**Comment by kbrabrand** [comment]
Ok. I guess we're godd then. Closing ticket.

**Comment by fangel** [comment]
I only have the lowercasing because it was in the original DSL that @christeredvartsen wrote for Imbo. 

But I think that was to get around case-sensitivity in MongoDB, so you could argue that the lowercasing should be done by the AST -> Mongo translation if necessary.

**Comment by kbrabrand** [comment]
Yes. It makes sense to do the lowercasing in the AST-> Mongo DSL transformation and keep the Imbo DSL to AST transformation as small as possible.
