### ISSUE TITLE
Remove lowercasing from Imbo DSL -> AST transformation

### ISSUE THREAD

**Issue by kbrabrand** [imbo/imbo-metadata-search#12]
The lowercasing of tokens in the AST parser was introduced as part of the Imbo DSL -> Mongo transformation initially written by @christeredvartsen, but is really more of a backend implementation detail. Some of the backends might need lowercasing, but the generic parser should't modify the data.

So for now, the lowercasing can be removed for now as the ES backend doesn't care for casing.

**Comment by fangel** [comment]
PR merged, so this issue is now resolved.
